window.VYBE_SUPABASE_URL = window.location.origin;
window.VYBE_SUPABASE_ANON_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTc3MDkxMjYwMCwiZXhwIjo0OTI2NTg2MjAwLCJyb2xlIjoiYW5vbiJ9.a3Mo99QbRu5Am1bqrzAYaASo92EqwYN6ILuvZrlTFbo";
window.VYBE_SUPABASE_BUCKET = "assets";
window.VYBE_SUPABASE_PREVIEW_BUCKET = "previews";
